FROM node:18 as node

WORKDIR /app

COPY . .

RUN npm install && npm run build

FROM nginx:alpine as nginx

WORKDIR /var/www/public

COPY --from=node /app/public .

COPY nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

RUN chown -R nginx:nginx /var/www && chmod -R 755 /var/www

# USER nginx

CMD ["nginx", "-g", "daemon off;"]

# COPY --from=node /app/build /usr/share/nginx/html

